vm:
  box: ubuntu/trusty64
  hostname: projects

providers:
  virtualbox:
    name: projects
    customize:
      - --cpus
      - 4
      - --memory
      - 2048
      - --pae
      - "on"
      - --paravirtprovider
      - kvm

network:
  private_network:
    ip: 192.168.113.202

timezone: Asia/Seoul

# Additional syncs
synced_folders:
  - src: ../../
    dest: /projects
    rsync__exclude:
      - .git/
      - node_modules/
