vm:
  box: ubuntu/trusty64
  hostname: projects

providers:
  virtualbox:
    name: projects
    customize:
      -
        - --cpus
        - 4
      -
        - --memory
        - 2048
      -
        - --pae
        - "on"

# Additional syncs
synced_folders:
  - src: ../../
    dest: /projects

default_path: /projects
