vm:
  box: ubuntu/trusty64
  hostname: projects

synced_folders:
  - src: ../../
    dest: /projects

providers:
  virtualbox:
    name: projects
    cpus: 4
    memory: 4096

default_path: /projects
