version: "3"

services:
  postgres:
    image: postgres:9-alpine
    networks:
      - postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:3-alpine
    networks:
      - redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

networks:
  postgres:
  redis:

volumes:
  postgres:
  redis:
